global:
  scrape_interval: 30m # Default scrape interval

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "go-gin-api"
    static_configs:
      - targets: ["gman-production.up.railway.app"] #maybe
    metrics_path: "/metrics"
    scrape_interval: 30m
